# Aliases
alias tree='tree -a -I .git'
alias orphans='pacman -Qqdt | xargs -ro sudo pacman -Rns'
alias pacinfo='pacman -Qi'
# alias cal='cal -3m'
alias cur-rem="printf '\033[?25l'"
alias cur-bacc="printf '\033[?25h'"
alias e='nvim'
alias ls='exa --color=always --icons'
alias l='exa --color=always --icons'
alias ll='exa --color=always --icons -lh'
alias la='exa --color=always --icons -ah'
alias lh='exa --color=always --icons -alh'
alias c='clear'
alias x='exit'
# alias lf='yazi'
alias xp='cd "$(xplr --print-pwd-as-result)"'
# alias cwd='ptpwd'
alias ncp='ncmpcpp' 
alias gayland='/usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland'
# alias ncp='$HOME/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug'
alias nohup='nohup $1 > ~/.cache/nohup.out'
# alias e='emacsclient -n -a emacs '
alias grep='rg -p'
alias find='fd -c always'
alias code='codium'
# alias nv='neovide'
alias startx='startx "$HOME/.config/X11/xinitrc" --"$XDG_CONFIG_HOME/X11/xserverrc" 2>~/.cache/xorg-errors.log 1>~/.cache/xorg.log'
alias stderr='echo "ls -l /proc/$(pidof -)/fd/2"'
alias search='sudo pacman -Fy'
# 1>~/.cache/xorg.log 2>~/.cache/xorg-errors.log'
alias fix-perms-windows='chmod -R a-x+X,u-x+rwX,go-wx+rX'
alias rm='rm -rf'
alias rt='trash'
# alias tar='tar xvzf'
alias nrf='neofetch --sixel $HOME/pictures/others/artworks/bouquet.png'
# alias nrf='neofetch --iterm2 ~/pictures/others/pfp/$(shuf -n 1 $(ls ~/pictures/others/pfp))'
# alias shuf-wall='rm ~/.cache/wallpaper && ln -s ~/Pictures/Wallpapers/$(ls -I "*.gif" -I "*.mp4" ~/Pictures/Wallpapers | shuf -n 1) ~/.cache/wallpaper'
alias weeb='weebsay'
# alias wprop='swaymsg -t get_tree | grep -i app_id'
alias clip-clear='rm -f ~/.cache/cliphist/db'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@'
alias gc='/usr/bin/git clone'
#alias gitlab-push="gitlab push origin main"
alias ..='cd ..'
# alias image='img2sixel'
alias wev='xev | awk -F'\''[ )]+'\'' '\''/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'\'''
# alias zzup='uguush -s -o fiery -F "https://zz.ht" -a 5379 -t "bdUVgjTkZMJXk2K1YyIdZU4v2TDKu7EPLX41lcdKhzRdtmexEOQtOwHkwCUFyKuj" -n'
