#!/bin/sh
while read file
do
  case "$1" in
    # "C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
    "C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
    "Delete")   mv -vf "$file" $HOME/.local/share/Trash/files  && notify-send "Trashed: $file";;
    "C-w")      sed -i -e '\@file@s@=.*@='"$file"'@' $HOME/.config/nitrogen/bg-saved.cfg && notify-send "Wallpaper changed"
    # "C-e")      while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
  esac
done
