#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map -repeat normal Super Return spawn footclient

# ==> Custom keybinds <==

riverctl map normal Super C focus-view previous
riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super G spawn "gtk3-widget-factory"
riverctl map normal Mod1  E spawn nautilus
riverctl map normal Super V spawn "$HOME/.scripts/lock.sh"
riverctl map normal Super Space spawn "env MOZ_ENABLE_WAYLAND=1 env MOZ_DBUS_REMOTE=1 firefox"

# Dunst keybinds

riverctl map normal Control Space spawn "dunstctl close"
riverctl map normal Control+Shift Space spawn "dunstctl close-all"
riverctl map normal Control Grave spawn "dunstctl history-pop"
riverctl map normal Control F1 spawn "dunstctl context"

# rofi keybinds

riverctl map normal Super D spawn "rofi -show drun"
riverctl map normal Super N spawn "rofi -show notes -modi notes:~/.scripts/rofi/notes.py"
riverctl map normal Mod1  N spawn "cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy"

# Screenshots keybinds

riverctl map normal None Scroll_Lock spawn "slurp | grim -g - - | wl-copy"
riverctl map normal Shift Scroll_Lock spawn "$HOME/.scripts/test.sh"

# Super+Q to close the focused view
riverctl map normal Super W close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift+Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Scratchpad
scratch_tag=$((1 << 20 ))
# Toggle the scratchpad 
riverctl map normal Mod4 Z toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad 
riverctl map normal Mod4 X set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super S toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
#riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
#riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
#riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    # riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None F3  spawn 'pamixer -i 5 --allow-boost'
    riverctl map $mode None F2  spawn 'pamixer -d 5 --allow-boost'
    riverctl map $mode None F4  spawn 'pamixer -t'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode Mod1 A   spawn 'playerctl play-pause'
    riverctl map $mode None F7  spawn 'mpc toggle'
    riverctl map $mode None XF86AudioStop  spawn 'mpc stop'
    riverctl map $mode None XF86AudioPrev  spawn 'mpc prev'
    riverctl map $mode None XF86AudioNext  spawn 'mpc next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None F9   spawn 'light -A 2'
    riverctl map $mode None F6   spawn 'light -U 2'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set window rules for certain windows
riverctl float-filter-add title "Picture-in-Picture"
riverctl float-filter-add title "Library"
riverctl float-filter-add title "mpv"
riverctl float-filter-add title "(?:Open|Save) (?:File|Folder|As)"
riverctl float-filter-add app-id "pavucontrol"
riverctl float-filter-add app-id "transmission-gtk"
riverctl float-filter-add app-id "engrampa"
riverctl float-filter-add app-id "nm-connection-editor"
riverctl float-filter-add title "popup title with spaces" 
# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Touchpad settings

riverctl input pointer-2-8-AlpsPS/2_ALPS_GlidePoint events enabled
# Enable natural scrolling
riverctl input pointer-2-8-AlpsPS/2_ALPS_GlidePoint natural-scroll enabled
# Enable tap to click
riverctl input pointer-2-8-AlpsPS/2_ALPS_GlidePoint tap enabled
# Enable tap button maps
riverctl input pointer-2-8-AlpsPS/2_ALPS_GlidePoint tap-button-map left-right-middle
# Disable while typing
riverctl input pointer-2-8-AlpsPS/2_ALPS_GlidePoint disable-while-typing enabled
# Disable natural scrolling
riverctl input pointer-2-8-AlpsPS/2_ALPS_GlidePoint natural-scroll disabled
# Disable laptop's internal keyboard
riverctl input keyboard-1-1-AT_Translated_Set_2_keyboard events disabled

# Focus follows cursor
riverctl focus-follows-cursor normal
riverctl focus-follows-cursor normal
# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
# Xcursor theme
riverctl xcursor-theme phinger-cursors 24

# Autostart Items
swaybg -i $HOME/.cache/wallpaper &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
foot --server &
wl-paste --watch cliphist store &
libinput-gestures-setup restart &
eww open bar &
/usr/bin/dunst &
systemctl --user import-environment DISPLAY &
# Rivertile
rivertile -view-padding 6 -outer-padding 6
