#!/bin/bash

killall -q sxhkd &
sxhkd -c ~/.config/berry/sxhkdrc &
$HOME/.config/awesome/autostart.sh &
# killall -q tint2
# tint2 &
killall -q -u anon touchegg &
touchegg &

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height       20
berryc edge_gap           20 0 0 0
# Set decoration colors
berryc focus_color         00ff00
berryc inner_focus_color   8378c6
berryc unfocus_color       292929
berryc inner_unfocus_color 292929
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Tewi-10"

# focus raises window!!!
berryc focus_follows_pointer "false"

# sane window modifiers
berryc move_mask "mod1"
berryc resize_mask "mod1"
berryc resize_button 3
